INSERT OR IGNORE INTO Types(Type, Kind) SELECT
Type,'KIND_BELIEF'
FROM NW_KAIJIANG_PANTHEONS;

INSERT OR IGNORE INTO Beliefs(BeliefType, Name, Description, BeliefClassType) SELECT
Type,'LOC_BELIEF_GOD_EXPANDING_NAME','LOC_BELIEF_GOD_EXPANDING_DESCRIPTION','BELIEF_CLASS_PANTHEON'
From NW_KAIJIANG_PANTHEONS;


INSERT OR IGNORE INTO BeliefModifiers (BeliefType, ModifierId) SELECT 
Type, 'MODIFIER_BELIEF_GOD_EXPANDING_SETTLER_CITIZEN_MODIFIER'
From NW_KAIJIANG_PANTHEONS UNION SELECT 
Type, 'MODIFIER_BELIEF_GOD_EXPANDING_population_MODIFIER'
From NW_KAIJIANG_PANTHEONS;