CREATE TABLE IF NOT EXISTS NW_KAIJIANG_PANTHEONS (
    Type TEXT,
    PRIMARY KEY(Type)
);
INSERT OR IGNORE INTO NW_KAIJIANG_PANTHEONS VALUES
('BELIEF_KAIJIANG1'),
('BELIEF_KAIJIANG2'),
('BELIEF_KAIJIANG3'),
('BELIEF_KAIJIANG4'),
('BELIEF_KAIJIANG5'),
('BELIEF_KAIJIANG6'),
('BELIEF_KAIJIANG7');