CREATE TABLE IF NOT EXISTS NW_KAIJIANG_PANTHEONS (
    Type TEXT,
    PRIMARY KEY(Type)
);
INSERT OR IGNORE INTO NW_KAIJIANG_PANTHEONS VALUES
('BELIEF_KAIJIANG1'),
('BELIEF_KAIJIANG2'),
('BELIEF_KAIJIANG3'),
('BELIEF_KAIJIANG4'),
('BELIEF_KAIJIANG5'),
('BELIEF_KAIJIANG6'),
('BELIEF_KAIJIANG7'),
('BELIEF_KAIJIANG8'),
('BELIEF_KAIJIANG9'),
('BELIEF_KAIJIANG10'),
('BELIEF_KAIJIANG11'),
('BELIEF_KAIJIANG12'),
('BELIEF_KAIJIANG13'),
('BELIEF_KAIJIANG14'),
('BELIEF_KAIJIANG15'),
('BELIEF_KAIJIANG16'),
('BELIEF_KAIJIANG17'),
('BELIEF_KAIJIANG18'),
('BELIEF_KAIJIANG19'),
('BELIEF_KAIJIANG20'),
('BELIEF_KAIJIANG21'),
('BELIEF_KAIJIANG22'),
('BELIEF_KAIJIANG23');