---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/4/12 16:41
---
-- ===========================================================================
-- 种资源
function NW_TPRF_ImprovementAddedToMap(iX, iY, iImprovement, iPlayer, iResource, Unknown1, Unknown2)
    local ImprovementType = GameInfo.Improvements[iImprovement].ImprovementType
	if GameInfo.NW_TPRF_IMPROVEMENT and GameInfo.NW_TPRF_IMPROVEMENT[ImprovementType] then
		local pPlot = Map.GetPlot(iX, iY)
		local iFeature = pPlot:GetFeatureType() or -1
		local iTerrain = pPlot:GetTerrainType()
		if iFeature > -1 then
			local sFeature = GameInfo.Features[iFeature].FeatureType
		end
		local sTerrain = GameInfo.Terrains[iTerrain].TerrainType

		ImprovementBuilder.SetImprovementType(pPlot, -1, NO_PLAYER)
		local TargetResource = GameInfo.NW_TPRF_IMPROVEMENT[ImprovementType].ResourceType;
        if GameInfo.Resources[TargetResource] and ResourceBuilder.CanHaveResource(pPlot,GameInfo.Resources[TargetResource].Index) then
			ResourceBuilder.SetResourceType(pPlot, GameInfo.Resources[TargetResource].Index, 1)
		else
            local pCapital = Players[iPlayer]:GetCities():GetCapitalCity()
			Game.AddWorldViewText(0, Locale.Lookup('LOC_NW_TPRF_RESOURCE_DISABLED'), iX, iY, 0);
			UnitManager.InitUnit(iPlayer, "UNIT_RESOURCE_ENGINEER", pCapital:GetX(), pCapital:GetY());
		end
	end
end

function initialize()
	Events.ImprovementAddedToMap.Add(NW_TPRF_ImprovementAddedToMap);
    print('NW_TPRF_Script Initialized Success.')
end

Events.LoadScreenClose.Add(initialize);
include('NW_TPRF_Script_',true);