-- 宣战
--UPDATE GlobalParameters SET Value='1' WHERE Name='DIPLOMACY_PEACE_MIN_TURNS';
UPDATE GlobalParameters SET Value='300' WHERE Name='DIPLOMACY_WAR_MIN_TURNS';
--抗尼战士 25 35 45 55
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='NIHANG_BARRACKS_STRENGTH' and Name='Amount';
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='NIHANG_ARMORY_STRENGTH' and Name='Amount';
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='NIHANG_ACADEMY_STRENGTH' and Name='Amount';
UPDATE Units SET CostProgressionParam1="15",Cost=190 WHERE UnitType='UNIT_LAHORE_NIHANG';


--==============================================================
--******			  C I T Y - S T A T E S				  ******
--==============================================================
-- 南马市中心+1文
/* <Row>
			<ModifierId>MINOR_CIV_NAN_MADOL_DISTRICTS_CULTURE_BONUS</ModifierId>
			<Name>Amount</Name>
			<Value>2</Value>
		</Row>

<Row>
			<ModifierId>MINOR_CIV_NAN_MADOL_DISTRICTS_CULTURE_BONUS</ModifierId>
			<ModifierType>MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE</ModifierType>
			<SubjectRequirementSetId>PLOT_IS_OR_ADJACENT_TO_COAST</SubjectRequirementSetId>
</Row>

INSERT OR IGNORE INTO Requirements ( RequirementId, RequirementType, Inverse )
	VALUES
		( 'REQUIRES_DISTRICT_IS_NOT_CITY_CENTER_BBG', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES', 1 ),
		( 'REQUIRES_DISTRICT_IS_NOT_AQUEDUCT_BBG', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES', 1 ),
		( 'REQUIRES_DISTRICT_IS_NOT_CANAL_BBG', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES', 1 ),
		( 'REQUIRES_DISTRICT_IS_NOT_DAM_BBG', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES', 1 ),
		( 'REQUIRES_DISTRICT_IS_NOT_NEIGHBORHOOD_BBG', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES', 1 ),
		( 'REQUIRES_DISTRICT_IS_NOT_SPACEPORT_BBG', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES', 1 ),
		( 'REQUIRES_DISTRICT_IS_NOT_WORLD_WONDER_BBG', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES', 1 );
INSERT OR IGNORE INTO RequirementArguments ( RequirementId, Name, Value )
	VALUES
		( 'REQUIRES_DISTRICT_IS_NOT_CITY_CENTER_BBG', 'DistrictType', 'DISTRICT_CITY_CENTER' ),
		( 'REQUIRES_DISTRICT_IS_NOT_AQUEDUCT_BBG', 'DistrictType', 'DISTRICT_AQUEDUCT' ),
		( 'REQUIRES_DISTRICT_IS_NOT_CANAL_BBG', 'DistrictType', 'DISTRICT_CANAL' ),
		( 'REQUIRES_DISTRICT_IS_NOT_DAM_BBG', 'DistrictType', 'DISTRICT_DAM' ),
		( 'REQUIRES_DISTRICT_IS_NOT_NEIGHBORHOOD_BBG', 'DistrictType', 'DISTRICT_NEIGHBORHOOD' ),
		( 'REQUIRES_DISTRICT_IS_NOT_SPACEPORT_BBG', 'DistrictType', 'DISTRICT_SPACEPORT' ),
		( 'REQUIRES_DISTRICT_IS_NOT_WORLD_WONDER_BBG', 'DistrictType', 'DISTRICT_WONDER' );
INSERT OR IGNORE INTO RequirementSets ( RequirementSetId, RequirementSetType )
	VALUES ( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIREMENTSET_TEST_ALL' );
INSERT OR IGNORE INTO RequirementSetRequirements ( RequirementSetId, RequirementId )
	VALUES
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_PLOT_IS_ADJACENT_TO_COAST' ),
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_DISTRICT_IS_NOT_CITY_CENTER_BBG' ),
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_DISTRICT_IS_NOT_AQUEDUCT_BBG' ),
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_DISTRICT_IS_NOT_CANAL_BBG' ),
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_DISTRICT_IS_NOT_DAM_BBG' ),
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_DISTRICT_IS_NOT_NEIGHBORHOOD_BBG' ),
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_DISTRICT_IS_NOT_SPACEPORT_BBG' ),
		( 'SPECIAL_DISTRICT_ON_COAST_BBG', 'REQUIRES_DISTRICT_IS_NOT_WORLD_WONDER_BBG' );
UPDATE Modifiers SET SubjectRequirementSetId='SPECIAL_DISTRICT_ON_COAST_BBG' WHERE ModifierId='MINOR_CIV_NAN_MADOL_DISTRICTS_CULTURE_BONUS'; */

--开洞
UPDATE Improvements SET PrereqTech='TECH_MILITARY_ENGINEERING' WHERE ImprovementType='IMPROVEMENT_MOUNTAIN_TUNNEL';

--战略政策
--马铁
UPDATE ModifierArguments SET Value='2' WHERE ModifierId='EQUESTRIAN_ORDERS_ADDITIONAL_HORSES_EXTRACTION' and Name='Amount';
UPDATE ModifierArguments SET Value='2' WHERE ModifierId='EQUESTRIAN_ORDERS_ADDITIONAL_IRON_EXTRACTION' and Name='Amount';
--政策提前
--马铁
update Policies set PrereqCivic="CIVIC_MILITARY_TRADITION" where PolicyType="POLICY_EQUESTRIAN_ORDERS";

--印尼改良
--UPDATE Improvement_YieldChanges SET YieldChange=2 WHERE ImprovementType="IMPROVEMENT_KAMPUNG" and YieldType='YIELD_PRODUCTION';

--苏格兰娱乐区速度
-- +50%娱乐区速度
INSERT INTO TraitModifiers (TraitType , ModifierId)
	VALUES
	('TRAIT_CIVILIZATION_SCOTTISH_ENLIGHTENMENT' , 'TRAIT_BOOST_AQUEDUCT_PRODUCTION_CPLMOD_SUGELAN');
INSERT INTO Modifiers (ModifierId , ModifierType , SubjectRequirementSetId )
	VALUES
	('TRAIT_BOOST_AQUEDUCT_PRODUCTION_CPLMOD_SUGELAN' , 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION' , NULL );
INSERT INTO ModifierArguments (ModifierId , Name , Value, Extra , SecondExtra)
	VALUES
	('TRAIT_BOOST_AQUEDUCT_PRODUCTION_CPLMOD_SUGELAN' , 'DistrictType' , 'DISTRICT_ENTERTAINMENT_COMPLEX', null , null ),
	('TRAIT_BOOST_AQUEDUCT_PRODUCTION_CPLMOD_SUGELAN' , 'Amount'       , '40'               , null , null );

--伐木工
--左1 +2食物-》+2食物1锤

INSERT INTO GovernorPromotionModifiers (GovernorPromotionType , ModifierId)
    VALUES
	("GOVERNOR_PROMOTION_RESOURCE_MANAGER_SURPLUS_LOGISTICS","SURPLUS_LOGISTICS_TRADE_ROUTE_PRODUCTION");
INSERT INTO	Modifiers (ModifierId , ModifierType)
	VALUES
	("SURPLUS_LOGISTICS_TRADE_ROUTE_PRODUCTION","MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS");
INSERT INTO ModifierArguments (ModifierId , Name , Value)
    VALUES
	("SURPLUS_LOGISTICS_TRADE_ROUTE_PRODUCTION","YieldType","YIELD_PRODUCTION");
INSERT INTO ModifierArguments (ModifierId , Name , Value)
    VALUES
	("SURPLUS_LOGISTICS_TRADE_ROUTE_PRODUCTION","Amount","0");
INSERT INTO ModifierArguments (ModifierId , Name , Value)
    VALUES
	("SURPLUS_LOGISTICS_TRADE_ROUTE_PRODUCTION","Domestic","true");

--左2 产能
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='INDUSTRIALIST_COAL_POWER_PLANT_PRODUCTION' AND Name='Amount';
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='INDUSTRIALIST_OIL_POWER_PLANT_PRODUCTION' AND Name='Amount';
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='INDUSTRIALIST_NUCLEAR_POWER_PLANT_PRODUCTION' AND Name='Amount';

--粱
--水产养殖 渔场城市就职+1生产力调整为+2
UPDATE ModifierArguments SET Value='2' WHERE ModifierId='FISHERY_GOVERNOR_PRODUCTION' AND Name='Amount';
--加固材料移至1级
INSERT INTO GovernorPromotionModifiers (GovernorPromotionType , ModifierId)
    VALUES
	("GOVERNOR_PROMOTION_BUILDER_GUILDMASTER","REINFORCED_INFRASTRUCTURE_PREVENET_STRUCTURAL_DAMAGE");
--加固材料
Delete FROM GovernorPromotionModifiers WHERE GovernorPromotionType='GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE' AND ModifierId='REINFORCED_INFRASTRUCTURE_PREVENET_STRUCTURAL_DAMAGE';

INSERT INTO GovernorPromotionModifiers (GovernorPromotionType,ModifierId)
	VALUES ('GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE','INFRASTRUCTURE_FASTER_MONUMENT_CONSTRUCTION1');
INSERT INTO GovernorPromotionModifiers (GovernorPromotionType,ModifierId)
	VALUES ('GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE','INFRASTRUCTURE_FASTER_GRANARY_CONSTRUCTION1');
INSERT INTO GovernorPromotionModifiers (GovernorPromotionType,ModifierId)
	VALUES ('GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE','INFRASTRUCTURE_FASTER_WATER_MILL_CONSTRUCTION1');
INSERT INTO GovernorPromotionModifiers (GovernorPromotionType,ModifierId)
	VALUES ('GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE','INFRASTRUCTURE_FASTER_SEWER_CONSTRUCTION1');
INSERT INTO GovernorPromotionModifiers (GovernorPromotionType,ModifierId)
	VALUES ('GOVERNOR_PROMOTION_REINFORCED_INFRASTRUCTURE','INFRASTRUCTURE_FASTER_GOVERNMENT_BUILDING_CONSTRUCTION1');
INSERT INTO Modifiers (ModifierId,ModifierType)
	VALUES ('INFRASTRUCTURE_FASTER_MONUMENT_CONSTRUCTION1','MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION');
INSERT INTO Modifiers (ModifierId,ModifierType)
	VALUES ('INFRASTRUCTURE_FASTER_GRANARY_CONSTRUCTION1','MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION');
INSERT INTO Modifiers (ModifierId,ModifierType)
	VALUES ('INFRASTRUCTURE_FASTER_WATER_MILL_CONSTRUCTION1','MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION');
INSERT INTO Modifiers (ModifierId,ModifierType)
	VALUES ('INFRASTRUCTURE_FASTER_SEWER_CONSTRUCTION1','MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION');
INSERT INTO Modifiers (ModifierId,ModifierType)
	VALUES ('INFRASTRUCTURE_FASTER_GOVERNMENT_BUILDING_CONSTRUCTION1','MODIFIER_SINGLE_CITY_ADJUST_BUILDING_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_MONUMENT_CONSTRUCTION1','BuildingType','BUILDING_MONUMENT');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_MONUMENT_CONSTRUCTION1','Amount','80');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_GRANARY_CONSTRUCTION1','BuildingType','BUILDING_GRANARY');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_GRANARY_CONSTRUCTION1','Amount','80');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_WATER_MILL_CONSTRUCTION1','BuildingType','BUILDING_WATER_MILL');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_WATER_MILL_CONSTRUCTION1','Amount','80');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_SEWER_CONSTRUCTION1','BuildingType','BUILDING_SEWER');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_SEWER_CONSTRUCTION1','Amount','80');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_GOVERNMENT_BUILDING_CONSTRUCTION1','DistrictType','DISTRICT_GOVERNMENT');
INSERT INTO ModifierArguments (ModifierId,Name,Value)
	VALUES ('INFRASTRUCTURE_FASTER_GOVERNMENT_BUILDING_CONSTRUCTION1','Amount','80');

--荷兰UI
--行政加锤
INSERT INTO Improvement_BonusYieldChanges (Id,ImprovementType,YieldType,BonusYieldChange,PrereqCivic)
	VALUES ('IMPROVEMENT_POLDER_PRODUCTION','IMPROVEMENT_POLDER','YIELD_PRODUCTION',"1","CIVIC_CIVIL_SERVICE");

--苏美尔UI
--INSERT INTO Improvement_BonusYieldChanges (Id , ImprovementType , YieldType , BonusYieldChange , PrereqCivic)
--	VALUES ('IMPROVEMENT_ZIGGURAT_2' , 'IMPROVEMENT_ZIGGURAT' , 'YIELD_FOOD' , '1' , 'CIVIC_FEUDALISM');
INSERT INTO Improvement_BonusYieldChanges (Id , ImprovementType , YieldType , BonusYieldChange , PrereqCivic)
	VALUES ('IMPROVEMENT_ZIGGURAT_3' , 'IMPROVEMENT_ZIGGURAT' , 'YIELD_PRODUCTION' , '1' , 'CIVIC_CONSERVATION');
--INSERT INTO Improvement_BonusYieldChanges (Id , ImprovementType , YieldType , BonusYieldChange , PrereqCivic)
--	VALUES ('IMPROVEMENT_ZIGGURAT_4' , 'IMPROVEMENT_ZIGGURAT' , 'YIELD_CULTURE' , '1' , 'CIVIC_HUMANISM');
--可以修在草原平原丘陵
--INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType)
--	VALUES ('IMPROVEMENT_ZIGGURAT' , 'TERRAIN_GRASS_HILLS');
--INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType)
--	VALUES ('IMPROVEMENT_ZIGGURAT' , 'TERRAIN_PLAINS_HILLS');	
--克里UI
--INSERT INTO Improvement_BonusYieldChanges (ID, ImprovementType, YieldType, BonusYieldChange, PrereqCivic)
--	VALUES ('IMPROVEMENT_MEKEWAP_25', 'IMPROVEMENT_MEKEWAP', 'YIELD_GOLD', 2, 'CIVIC_GUILDS');	
INSERT INTO Improvement_BonusYieldChanges (ID, ImprovementType, YieldType, BonusYieldChange, PrereqCivic)
	VALUES ('IMPROVEMENT_MEKEWAP_26', 'IMPROVEMENT_MEKEWAP', 'YIELD_PRODUCTION', 1, 'CIVIC_MERCANTILISM');	
INSERT INTO Improvement_BonusYieldChanges (ID, ImprovementType, YieldType, BonusYieldChange, PrereqCivic)
	VALUES ('IMPROVEMENT_MEKEWAP_27', 'IMPROVEMENT_MEKEWAP', 'YIELD_GOLD', 2, 'CIVIC_CONSERVATION');	
	
--瑞娜
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='FOREIGN_EXCHANGE_GOLD_FROM_FOREIGN_TRADE_PASSING_THROUGH' AND Name='Amount';
--守备官
--左1-4力
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='GARRISON_COMMANDER_ADJUST_CITY_COMBAT_BONUS' AND Name='Amount';
--1级-4力
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='DEFENDER_ADJUST_CITY_DEFENSE_STRENGTH' AND Name='Amount';

	
--挪威UU
UPDATE Units SET Combat=32 WHERE UnitType='UNIT_NORWEGIAN_LONGSHIP';
	
--迦太基UU
UPDATE Units SET Combat=31,Cost=65 WHERE UnitType='UNIT_PHOENICIA_BIREME';

--娱乐区
UPDATE Districts SET Entertainment=2 where DistrictType="DISTRICT_ENTERTAINMENT_COMPLEX";
UPDATE Districts SET Entertainment=2 where DistrictType="DISTRICT_WATER_ENTERTAINMENT_COMPLEX";


--战争之神

UPDATE ModifierArguments SET Value='GOD_OF_WAR_FATH' WHERE Value='GOD_OF_WAR_FAITH_KILLS_MODIFIER' AND ModifierId='GOD_OF_WAR_FAITH_KILLS';
INSERT INTO Modifiers (ModifierId , ModifierType)
	VALUES ('GOD_OF_WAR_FATH' , 'MODIFIER_PLAYER_UNITS_ADJUST_POST_COMBAT_YIELD');
INSERT INTO ModifierArguments (ModifierId , Name , Value) 
	VALUES ('GOD_OF_WAR_FATH' , 'YieldType' , 'YIELD_GOLD');
INSERT INTO ModifierArguments (ModifierId , Name , Value) 
	VALUES ('GOD_OF_WAR_FATH' , 'PercentDefeatedStrength' , '0');

--丰产
UPDATE ModifierArguments SET Value='0' WHERE Name='Amount' AND ModifierId='FERTILITY_RITES_GROWTH';

--启蒙会 BELIEF_INITIATION_RITES
INSERT OR REPLACE INTO Types (Type, Kind)
    VALUES ('MODIFIER_ALL_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'KIND_MODIFIER');
INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
    VALUES ('MODIFIER_ALL_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'COLLECTION_ALL_CITIES', 'EFFECT_ADJUST_BUILDING_YIELD_CHANGE');
	
--UPDATE ModifierArguments SET Value='RELIGIOUS_SETTLEMENTS_PALACE_YIELD_FAITH' WHERE Name='ModifierId' AND ModifierId='INITIATION_RITES_FAITH_DISPERSAL';

--INSERT INTO BeliefModifiers (BeliefType, ModifierId) VALUES
--('BELIEF_INITIATION_RITES', 'RELIGIOUS_SETTLEMENTS_PALACE_YIELD_FAITH');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('RELIGIOUS_SETTLEMENTS_PALACE_YIELD_FAITH', 'MODIFIER_ALL_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('RELIGIOUS_SETTLEMENTS_PALACE_YIELD_FAITH', 'BuildingType', 'BUILDING_MONUMENT'),
('RELIGIOUS_SETTLEMENTS_PALACE_YIELD_FAITH', 'YieldType',    'YIELD_FAITH'),
('RELIGIOUS_SETTLEMENTS_PALACE_YIELD_FAITH', 'Amount',       '3');
--大地
UPDATE ModifierArguments SET Value='1' WHERE ModifierId='EARTH_GODDESS_APPEAL_FAITH_MODIFIER' AND Name='Amount';
UPDATE RequirementArguments SET Value='3' WHERE RequirementId='REQUIRES_PLOT_BREATHTAKING_APPEAL' AND Name='MinimumAppeal';


--梁 实力公园 +1食物
INSERT INTO Improvement_YieldChanges (ImprovementType, YieldType, YieldChange) VALUES
('IMPROVEMENT_CITY_PARK', 'YIELD_FOOD', '1');
INSERT INTO Improvement_YieldChanges (ImprovementType, YieldType, YieldChange) VALUES
('IMPROVEMENT_CITY_PARK', 'YIELD_GOLD', '2');

--大主教回血
UPDATE ModifierArguments SET Value='80' WHERE ModifierId='CARDINAL_LAYING_ON_OF_HANDS_RELIGIOUS_HEAL' AND Name='Amount';
UPDATE ModifierArguments SET Value='80' WHERE ModifierId='CARDINAL_LAYING_ON_OF_HANDS_HEAL' AND Name='Amount';

--克里
UPDATE Units SET Combat=14, Cost=35 WHERE UnitType='UNIT_CREE_OKIHTCITAW';

--毛利UU
--DELETE FROM	UnitReplaces WHERE CivUniqueUnitType="UNIT_MAORI_TOA"  and  ReplacesUnitType="UNIT_SWORDSMAN";
UPDATE Units SET StrategicResource="RESOURCE_IRON" WHERE UnitType="UNIT_MAORI_TOA";
--UPDATE Units_XP2 SET ResourceCost="10" WHERE UnitType="UNIT_MAORI_TOA";
UPDATE Units_XP2 SET ResourceCost=20 WHERE UnitType="UNIT_MAORI_TOA";

--波斯庭院
INSERT INTO Improvement_YieldChanges (ImprovementType , YieldType,YieldChange)
 VALUES ("IMPROVEMENT_PAIRIDAEZA" , "YIELD_FOOD" , "1");


--靖扶骑兵
UPDATE Units SET Cost=200,Combat=50 WHERE UnitType='UNIT_BYZANTINE_TAGMA';
--相邻军事单位+2力
UPDATE ModifierArguments SET Value=1 WHERE ModifierId='TAGMA_COMBAT_STRENGTH' and Name="Amount";
--喷火船+3
UPDATE ModifierArguments SET Value=3 WHERE ModifierId='DROMON_COMBAT_STRENGTH_AGAINST_UNITS' and Name="Amount";



--烂地夫人
DELETE FROM	RequirementSetRequirements WHERE RequirementSetId="PLOT_HAS_REEDS_REQUIREMENTS" and RequirementId="REQUIRES_PLOT_HAS_FLOODPLAINS";
--1
INSERT INTO BeliefModifiers (BeliefType, ModifierId)
	VALUES ('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES', 'LADY_OF_THE_REEDS_PRODUCTION_TBLNEW');
INSERT INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW', 'ModifierId','LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers');

INSERT INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW', 'REQUIRES_PLOT_HAS_FLOODPLAINS');
--INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
--	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW', 'REQUIRES_PLOT_HAS_NO_IMPROVEMENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers', 'YieldType','YIELD_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers', 'Amount','1');
--2
/*
INSERT INTO BeliefModifiers (BeliefType, ModifierId)
	VALUES ('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES', 'LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_2');
INSERT INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_2', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_2', 'ModifierId','LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_2');

INSERT INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_2', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_2');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_2', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_2', 'REQUIRES_PLOT_HAS_FLOODPLAINS_GRASSLAND');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_2', 'REQUIRES_PLOT_HAS_NO_IMPROVEMENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_2', 'YieldType','YIELD_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_2', 'Amount','2');
--3
INSERT INTO BeliefModifiers (BeliefType, ModifierId)
	VALUES ('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES', 'LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_3');
INSERT INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_3', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_3', 'ModifierId','LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_3');

INSERT INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_3', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_3');
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_3', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_3', 'REQUIRES_PLOT_HAS_FLOODPLAINS_PLAINS');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
	VALUES ('PLOT_HAS_REEDS_REQUIREMENTS_TBLNEW_3', 'REQUIRES_PLOT_HAS_NO_IMPROVEMENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_3', 'YieldType','YIELD_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
	VALUES ('LADY_OF_THE_REEDS_PRODUCTION_TBLNEW_Modifiers_3', 'Amount','2');
	*/
--
--烂地女神 草原泛滥 平原泛滥
INSERT INTO Requirements (RequirementId, RequirementType)
	VALUES ('REQUIRES_PLOT_HAS_FLOODPLAINS_GRASSLAND', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES');
INSERT INTO Requirements (RequirementId, RequirementType)
	VALUES ('REQUIRES_PLOT_HAS_FLOODPLAINS_PLAINS', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value)
	VALUES ('REQUIRES_PLOT_HAS_FLOODPLAINS_GRASSLAND', 'FeatureType', 'FEATURE_FLOODPLAINS_GRASSLAND');
INSERT INTO RequirementArguments (RequirementId, Name, Value)
	VALUES ('REQUIRES_PLOT_HAS_FLOODPLAINS_PLAINS', 'FeatureType', 'FEATURE_FLOODPLAINS_PLAINS');

UPDATE Building_YieldChanges SET YieldChange=1 WHERE BuildingType='BUILDING_GURDWARA' and YieldType="YIELD_FOOD";

--纳札加姆
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='MINOR_CIV_NGAZARGAMU_BARRACKS_STABLE_PURCHASE_BONUS' AND Name='Amount';
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='MINOR_CIV_NGAZARGAMU_ARMORY_PURCHASE_BONUS' AND Name='Amount';
UPDATE ModifierArguments SET Value='10' WHERE ModifierId='MINOR_CIV_NGAZARGAMU_MILITARY_ACADEMY_PURCHASE_BONUS' AND Name='Amount';


--遗物箱
UPDATE ModifierArguments SET Value='200' WHERE ModifierId='RELIQUARIES_RELIC_TOURISM_MODIFIER' AND Name='ScalingFactor';

--
	
	
--巴西娱乐区
UPDATE Districts SET Entertainment=3 where DistrictType="DISTRICT_STREET_CARNIVAL";
UPDATE Districts SET Entertainment=3 where DistrictType="DISTRICT_WATER_STREET_CARNIVAL";


--祖鲁矛
UPDATE Units SET Combat=44 WHERE UnitType="UNIT_ZULU_IMPI";


--砍二抓工人
--移除雄鹰战士基础抓工人能力
Delete From TypeTags WHERE Type="UNIT_AZTEC_EAGLE_WARRIOR" AND  Tag="CLASS_CAPTURE_WORKER";
--抓工人能力适用所有近战
INSERT INTO TypeTags (Type, Tag)
	VALUES ('ABILITY_CAPTIVE_WORKERS', 'CLASS_MELEE');
UPDATE UnitAbilities SET Inactive=1 WHERE UnitAbilityType='ABILITY_CAPTIVE_WORKERS';
--赋予所有近战能力
INSERT INTO Modifiers (ModifierId, ModifierType,Permanent)
	VALUES ('TRAIT_KANER_EMBARKED_ABILITY', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',1);
INSERT INTO ModifierArguments (ModifierId, Name ,Value)
	VALUES ('TRAIT_KANER_EMBARKED_ABILITY', 'AbilityType','ABILITY_CAPTIVE_WORKERS');
INSERT INTO TraitModifiers (TraitType, ModifierId)
	VALUES ('TRAIT_CIVILIZATION_LEGEND_FIVE_SUNS', 'TRAIT_KANER_EMBARKED_ABILITY');

--修复间谍
DELETE FROM Types WHERE Type="NOTIFICATION_SPY_FLED_CITY" and Kind="KIND_NOTIFICATION";

--投石车-》海军近战+5力
INSERT INTO Types (Type, Kind)
	VALUES ('ABILITY_SIEGE_TO_NAVAL_MELEE', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag)
	VALUES ('ABILITY_SIEGE_TO_NAVAL_MELEE', 'CLASS_SIEGE');
INSERT INTO UnitAbilities (UnitAbilityType, Name ,Description)
	VALUES ('ABILITY_SIEGE_TO_NAVAL_MELEE', 'LOC_ABILITY_SIEGE_TO_NAVAL_MELEE_NAME','LOC_ABILITY_SIEGE_TO_NAVAL_MELEE_DESCRIPTION');
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId)
	VALUES ('ABILITY_SIEGE_TO_NAVAL_MELEE', 'ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE');

INSERT INTO Modifiers (ModifierId, ModifierType,SubjectRequirementSetId)
	VALUES ('ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH','ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name ,Value)
	VALUES ('ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE', 'Amount','5');
INSERT INTO ModifierStrings (ModifierId, Context ,Text)
	VALUES ('ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE', 'Preview','LOC_ABILITY_SIEGE_TO_NAVAL_MELEE_DESCRIPTION');

INSERT INTO RequirementSets (RequirementSetId , RequirementSetType)
	VALUES ('ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE_REQUIREMENTS' , 'REQUIREMENTSET_TEST_ANY');	
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId)
	VALUES ('ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE_REQUIREMENTS' , 'ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE_REQUIREMENTS_NAVAL_MELEE'); 
INSERT INTO Requirements (RequirementId , RequirementType)
	VALUES ('ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE_REQUIREMENTS_NAVAL_MELEE' , 'REQUIREMENT_OPPONENT_UNIT_TAG_MATCHES');
INSERT INTO RequirementArguments (RequirementId , Name , Value)
	VALUES ('ANTI_ABILITY_SIEGE_TO_NAVAL_MELEE_REQUIREMENTS_NAVAL_MELEE' , 'Tag','CLASS_NAVAL_MELEE');  



--武僧
--条件

INSERT INTO RequirementSets (RequirementSetId , RequirementSetType)
	VALUES ('UNIT_IS_WARRIOR_NEW' , 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId)
	VALUES ('UNIT_IS_WARRIOR_NEW' , 'REQUIREMENT_UNIT_IS_WARRIOR_NEW');
INSERT INTO Requirements (RequirementId , RequirementType)
	VALUES ('REQUIREMENT_UNIT_IS_WARRIOR_NEW' , 'REQUIREMENT_UNIT_TYPE_MATCHES');	
INSERT INTO RequirementArguments(RequirementId , Name, Value)
	VALUES ('REQUIREMENT_UNIT_IS_WARRIOR_NEW', 'UnitType',"UNIT_WARRIOR_MONK"); 
--加力
--政治哲学
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_POLITICAL_PHILOSOPHY' , 'CIVIC_POLITICAL_PHILOSOPHY_FOR_WORRIOR');
INSERT INTO ModifierStrings(ModifierId , Context, Text)
	VALUES ('CIVIC_POLITICAL_PHILOSOPHY_FOR_WORRIOR', 'Preview',"政治哲学 +5[ICON_Strength] 战斗力(文化成长)"); 
INSERT INTO Modifiers(ModifierId , ModifierType, SubjectRequirementSetId)
	VALUES ('CIVIC_POLITICAL_PHILOSOPHY_FOR_WORRIOR', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH',"UNIT_IS_WARRIOR_NEW"); 	
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('CIVIC_POLITICAL_PHILOSOPHY_FOR_WORRIOR', 'Amount',"5");
--王权
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_DIVINE_RIGHT' , 'CIVIC_DIVINE_RIGHT_FOR_WORRIOR');
INSERT INTO ModifierStrings(ModifierId , Context, Text)
	VALUES ('CIVIC_DIVINE_RIGHT_FOR_WORRIOR', 'Preview',"王权神授 +7[ICON_Strength] 战斗力(文化成长)"); 
INSERT INTO Modifiers(ModifierId , ModifierType, SubjectRequirementSetId)
	VALUES ('CIVIC_DIVINE_RIGHT_FOR_WORRIOR', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH',"UNIT_IS_WARRIOR_NEW"); 	
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('CIVIC_DIVINE_RIGHT_FOR_WORRIOR', 'Amount',"7");
--归正会
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_REFORMED_CHURCH' , 'CIVIC_REFORMED_CHURCH_FOR_WORRIOR');
INSERT INTO ModifierStrings(ModifierId , Context, Text)
	VALUES ('CIVIC_REFORMED_CHURCH_FOR_WORRIOR', 'Preview',"归正会 +7[ICON_Strength] 战斗力(文化成长)"); 
INSERT INTO Modifiers(ModifierId , ModifierType, SubjectRequirementSetId)
	VALUES ('CIVIC_REFORMED_CHURCH_FOR_WORRIOR', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH',"UNIT_IS_WARRIOR_NEW"); 	
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('CIVIC_REFORMED_CHURCH_FOR_WORRIOR', 'Amount',"7");
--加信仰
--政治哲学
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_POLITICAL_PHILOSOPHY' , 'ZHEKOU_FOR_WORRIOR_1');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_1', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1', 'Amount',"0");
--历史记录
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_RECORDED_HISTORY' , 'ZHEKOU_FOR_WORRIOR_1_1');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_1', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_1', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_1', 'Amount',"-20");
--防御战术
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_DEFENSIVE_TACTICS' , 'ZHEKOU_FOR_WORRIOR_1_2');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_2', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_2', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_2', 'Amount',"-20");
--行政部门
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_CIVIL_SERVICE' , 'ZHEKOU_FOR_WORRIOR_1_3');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_3', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_3', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_1_3', 'Amount',"-20");

--王权
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_DIVINE_RIGHT' , 'ZHEKOU_FOR_WORRIOR_2');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_2', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_2', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_2', 'Amount',"-10");

--公会
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_GUILDS' , 'ZHEKOU_FOR_WORRIOR_2_1');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_2_1', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_2_1', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_2_1', 'Amount',"-20");

--归正会
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_REFORMED_CHURCH' , 'ZHEKOU_FOR_WORRIOR_3');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_3', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_3', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_3', 'Amount',"-30");

--封建主义
INSERT INTO CivicModifiers (CivicType , ModifierId)
	VALUES ('CIVIC_FEUDALISM' , 'ZHEKOU_FOR_WORRIOR_3_2');
INSERT INTO Modifiers(ModifierId , ModifierType)
	VALUES ('ZHEKOU_FOR_WORRIOR_3_2', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST'); 
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_3_2', 'UnitType',"UNIT_WARRIOR_MONK");
INSERT INTO ModifierArguments(ModifierId , Name, Value)
	VALUES ('ZHEKOU_FOR_WORRIOR_3_2', 'Amount',"-20");
	
--宗教议会
UPDATE ModifierArguments SET Value='5' WHERE ModifierId='WC_RES_RELIGIOUS_UNITS_STRENGTH' AND Name='Amount';
