--============================================================
-- Lua Support
--============================================================
CREATE TABLE IF NOT EXISTS Nwflower_MOD_Traits
(
    TraitType TEXT NOT NULL,
    PRIMARY KEY (TraitType),
    FOREIGN KEY (TraitType) REFERENCES Traits (TraitType) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT OR IGNORE INTO Nwflower_MOD_Traits(TraitType)
SELECT TraitType
FROM Traits;

INSERT OR IGNORE INTO TraitModifiers(TraitType, ModifierId)
SELECT TraitType,
       'MODFEAT_TRAIT_PROPERTY_' || TraitType
FROM Nwflower_MOD_Traits;

INSERT OR IGNORE INTO Modifiers(ModifierId, ModifierType)
SELECT 'MODFEAT_TRAIT_PROPERTY_' || TraitType,
       'MODIFIER_PLAYER_ADJUST_PROPERTY'
FROM Nwflower_MOD_Traits;

INSERT OR IGNORE INTO ModifierArguments(ModifierId, Name, Value)
SELECT 'MODFEAT_TRAIT_PROPERTY_' || TraitType,
       'Key',
       'PROPERTY_' || TraitType
FROM Nwflower_MOD_Traits
UNION
SELECT 'MODFEAT_TRAIT_PROPERTY_' || TraitType,
       'Amount',
       1
FROM Nwflower_MOD_Traits;

--============================================================
-- RequirementSet
--============================================================
-- 条件集：城市拥有某区域
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_CITY_HAS_' || DistrictType, 'REQUIREMENTSET_TEST_ALL'
FROM Districts;
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_CITY_HAS_' || DistrictType, 'NW_CITY_HAS_' || DistrictType || '_REQUIREMENT'
FROM Districts;
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_CITY_HAS_' || DistrictType || '_REQUIREMENT', 'REQUIREMENT_CITY_HAS_DISTRICT'
FROM Districts;
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_CITY_HAS_' || DistrictType || '_REQUIREMENT', 'DistrictType', DistrictType
FROM Districts;

-- 条件集：区域是任意专业化区域
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('NW_IS_SPECIALTY_DISTRICT', 'REQUIREMENTSET_TEST_ANY');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT 'NW_IS_SPECIALTY_DISTRICT', 'NW_DISTRICT_IS_' || DistrictType || '_REQUIREMENT'
FROM Districts
WHERE RequiresPopulation = 1;

-- 条件集：区域类型匹配
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_DISTRICT_IS_' || DistrictType, 'REQUIREMENTSET_TEST_ALL'
FROM Districts;
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_DISTRICT_IS_' || DistrictType, 'NW_DISTRICT_IS_' || DistrictType || '_REQUIREMENT'
FROM Districts;
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_DISTRICT_IS_' || DistrictType || '_REQUIREMENT', 'REQUIREMENT_DISTRICT_TYPE_MATCHES'
FROM Districts;
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_DISTRICT_IS_' || DistrictType || '_REQUIREMENT', 'DistrictType', DistrictType
FROM Districts;


-- 城市拥有某改良资源
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
SELECT 'NW_CITY_HAS_IMPROVED_' || Resources.ResourceType || '_REQ',
       'REQUIREMENT_CITY_HAS_RESOURCE_TYPE_IMPROVED'
FROM Resources
WHERE NOT Resources.ResourceType = 'NW_DUMMY_RESOURCE_MACEDON';
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value)
SELECT 'NW_CITY_HAS_IMPROVED_' || Resources.ResourceType || '_REQ',
       'ResourceType',
       Resources.ResourceType
FROM Resources
WHERE NOT Resources.ResourceType = 'NW_DUMMY_RESOURCE_MACEDON';

-- 城市拥有任意改良战略
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('NW_CITY_HAS_IMPROVED_STRAT_REQSET', 'REQUIREMENTSET_TEST_ANY');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT 'NW_CITY_HAS_IMPROVED_STRAT_REQSET',
       'NW_CITY_HAS_IMPROVED_' || Resources.ResourceType || '_REQ'
FROM Resources
WHERE ResourceClassType = 'RESOURCECLASS_STRATEGIC';
-- 城市拥有任意改良加成
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('NW_CITY_HAS_IMPROVED_BONUS_REQSET', 'REQUIREMENTSET_TEST_ANY');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT 'NW_CITY_HAS_IMPROVED_BONUS_REQSET',
       'NW_CITY_HAS_IMPROVED_' || Resources.ResourceType || '_REQ'
FROM Resources
WHERE ResourceClassType = 'RESOURCECLASS_BONUS';
-- 城市拥有任意改良奢侈
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('NW_CITY_HAS_IMPROVED_LUX_REQSET', 'REQUIREMENTSET_TEST_ANY');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
SELECT 'NW_CITY_HAS_IMPROVED_LUX_REQSET',
       'NW_CITY_HAS_IMPROVED_' || Resources.ResourceType || '_REQ'
FROM Resources
WHERE ResourceClassType = 'RESOURCECLASS_LUXURY';

-- 玩家拥有某科技
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_PLAYER_HAS_' || TechnologyType, 'REQUIREMENTSET_TEST_ALL'
FROM Technologies;
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_UTILS_PLAYER_HAS_' || TechnologyType || '_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'
FROM Technologies;
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_UTILS_PLAYER_HAS_' || TechnologyType || '_REQUIREMENT', 'TechnologyType', TechnologyType
FROM Technologies;
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_PLAYER_HAS_' || TechnologyType, 'NW_UTILS_PLAYER_HAS_' || TechnologyType || '_REQUIREMENT'
FROM Technologies;

-- 玩家拥有某市政
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_PLAYER_HAS_' || CivicType, 'REQUIREMENTSET_TEST_ALL'
FROM Civics;
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_UTILS_PLAYER_HAS_' || CivicType || '_REQUIREMENT', 'REQUIREMENT_PLAYER_HAS_CIVIC'
FROM Civics;
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_UTILS_PLAYER_HAS_' || CivicType || '_REQUIREMENT', 'CivicType', CivicType
FROM Civics;
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_PLAYER_HAS_' || CivicType, 'NW_UTILS_PLAYER_HAS_' || CivicType || '_REQUIREMENT'
FROM Civics;


-- 玩家是某指定领袖
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_PLAYER_IS_' || LeaderType, 'REQUIREMENTSET_TEST_ANY'
FROM Leaders
WHERE InheritFrom = 'LEADER_DEFAULT';
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_PLAYER_IS_' || LeaderType, 'NW_PLAYER_IS_' || LeaderType || '_REQUIREMENT'
FROM Leaders
WHERE InheritFrom = 'LEADER_DEFAULT';
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_PLAYER_IS_' || LeaderType || '_REQUIREMENT', 'REQUIREMENT_PLAYER_LEADER_TYPE_MATCHES'
FROM Leaders
WHERE InheritFrom = 'LEADER_DEFAULT';
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_PLAYER_IS_' || LeaderType || '_REQUIREMENT', 'LeaderType', LeaderType
FROM Leaders
WHERE InheritFrom = 'LEADER_DEFAULT';

-- 玩家可见某资源
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('NW_PLAYER_CAN_SEE_HORSES', 'REQUIREMENTSET_TEST_ALL'),
       ('NW_PLAYER_CAN_SEE_IRON', 'REQUIREMENTSET_TEST_ALL'),
       ('NW_PLAYER_CAN_SEE_NITER', 'REQUIREMENTSET_TEST_ALL'),
       ('NW_PLAYER_CAN_SEE_COAL', 'REQUIREMENTSET_TEST_ALL'),
       ('NW_PLAYER_CAN_SEE_ALUMINUM', 'REQUIREMENTSET_TEST_ALL'),
       ('NW_PLAYER_CAN_SEE_OIL', 'REQUIREMENTSET_TEST_ALL'),
       ('NW_PLAYER_CAN_SEE_URANIUM', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('NW_PLAYER_CAN_SEE_HORSES', 'REQUIRES_PLAYER_CAN_SEE_HORSES'),
       ('NW_PLAYER_CAN_SEE_IRON', 'REQUIRES_PLAYER_CAN_SEE_IRON'),
       ('NW_PLAYER_CAN_SEE_NITER', 'REQUIRES_PLAYER_CAN_SEE_NITER'),
       ('NW_PLAYER_CAN_SEE_COAL', 'REQUIRES_PLAYER_CAN_SEE_COAL'),
       ('NW_PLAYER_CAN_SEE_ALUMINUM', 'REQUIRES_PLAYER_CAN_SEE_ALUMINUM'),
       ('NW_PLAYER_CAN_SEE_OIL', 'REQUIRES_PLAYER_CAN_SEE_OIL'),
       ('NW_PLAYER_CAN_SEE_URANIUM', 'REQUIRES_PLAYER_CAN_SEE_URANIUM');

-- 游戏所处时代
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_GAME_IS_IN_' || EraType || '_REQUIREMENT', 'REQUIREMENT_GAME_ERA_IS'
FROM Eras;
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_GAME_IS_IN_' || EraType || '_REQUIREMENT', 'EraType', EraType
FROM Eras;
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_GAME_IS_IN_' || EraType, 'REQUIREMENTSET_TEST_ALL'
FROM Eras;
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_GAME_IS_IN_' || EraType, 'NW_GAME_IS_IN_' || EraType || '_REQUIREMENT'
FROM Eras;

-- 玩家所处某某时代及之后
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_PLAYER_IS_IN_' || EraType || '_REQUIREMENT', 'REQUIREMENT_PLAYER_ERA_AT_LEAST'
FROM Eras;
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_PLAYER_IS_IN_' || EraType || '_REQUIREMENT', 'EraType', EraType
FROM Eras;
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_PLAYER_IS_IN_' || EraType, 'REQUIREMENTSET_TEST_ALL'
FROM Eras;
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_PLAYER_IS_IN_' || EraType, 'NW_PLAYER_IS_IN_' || EraType || '_REQUIREMENT'
FROM Eras;

-- 玩家所处某某时代之前
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType, Inverse)
SELECT 'NW_PLAYER_IS_NOT_IN_' || EraType || '_REQUIREMENT', 'REQUIREMENT_PLAYER_ERA_AT_LEAST', 1
FROM Eras;
INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Value)
SELECT 'NW_PLAYER_IS_NOT_IN_' || EraType || '_REQUIREMENT', 'EraType', EraType
FROM Eras;
INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_PLAYER_IS_NOT_IN_' || EraType, 'REQUIREMENTSET_TEST_ALL'
FROM Eras;
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_PLAYER_IS_NOT_IN_' || EraType, 'NW_PLAYER_IS_NOT_IN_' || EraType || '_REQUIREMENT'
FROM Eras;

-- 单位在丘陵上
INSERT OR IGNORE INTO RequirementSets
VALUES ('NW_UNIT_ON_HILL_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements
VALUES ('NW_UNIT_ON_HILL_REQUIREMENTS', 'PLOT_IS_HILLS_REQUIREMENT');

-- 单元格有加成资源
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
VALUES ('NW_REQUIRES_PLOT_HAS_IMPROVED_BONUS', 'REQUIREMENT_PLOT_IMPROVED_RESOURCE_CLASS_TYPE_MATCHES');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('NW_REQUIRES_PLOT_HAS_IMPROVED_BONUS', 'ResourceClassType', 'RESOURCECLASS_BONUS');

-- 单元格有奢侈资源
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
VALUES ('NW_REQUIRES_PLOT_HAS_IMPROVED_LUXURY', 'REQUIREMENT_PLOT_IMPROVED_RESOURCE_CLASS_TYPE_MATCHES');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('NW_REQUIRES_PLOT_HAS_IMPROVED_LUXURY', 'ResourceClassType', 'RESOURCECLASS_LUXURY');

-- 单元格被改良
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
VALUES ('NW_TILE_HAS_ANY_IMPROVEMENT', 'REQUIREMENT_PLOT_HAS_ANY_IMPROVEMENT');

--modifier types
INSERT OR IGNORE INTO Types(Type, Kind)
VALUES ('MODIFIER_SINGLE_PLAYER_ATTACH_MODIFIER', 'KIND_MODIFIER'),
       ('MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER', 'KIND_MODIFIER');
INSERT OR IGNORE INTO DynamicModifiers(ModifierType, CollectionType, EffectType)
VALUES ('MODIFIER_SINGLE_PLAYER_ATTACH_MODIFIER', 'COLLECTION_OWNER', 'EFFECT_ATTACH_MODIFIER'),
       ('MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER', 'COLLECTION_PLAYER_DISTRICTS', 'EFFECT_ATTACH_MODIFIER');


-- 玩家是某类城邦的宗主国
INSERT OR IGNORE INTO Requirements(RequirementId, RequirementType)
SELECT 'NW_PLAYER_IS_SUZERAIN_OF_' || LeaderType, 'REQUIREMENT_PLAYER_IS_SUZERAIN_OF_X'
FROM Leaders
WHERE InheritFrom IN
      ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
       'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');

INSERT OR IGNORE INTO RequirementArguments(RequirementId, Name, Type, Value)
SELECT 'NW_PLAYER_IS_SUZERAIN_OF_' || LeaderType, 'LeaderType', 'ARGTYPE_IDENTITY', LeaderType
FROM Leaders
WHERE InheritFrom IN
      ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
       'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');

INSERT OR IGNORE INTO RequirementSets(RequirementSetId, RequirementSetType)
SELECT 'NW_PLAYER_IS_SUZERAIN_OF_' || LeaderType || '_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'
FROM Leaders
WHERE InheritFrom IN
      ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
       'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');

INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId, RequirementId)
SELECT 'NW_PLAYER_IS_SUZERAIN_OF_' || LeaderType || '_REQUIREMENTS', 'NW_PLAYER_IS_SUZERAIN_OF_' || LeaderType
FROM Leaders
WHERE InheritFrom IN
      ('LEADER_MINOR_CIV_CULTURAL', 'LEADER_MINOR_CIV_INDUSTRIAL', 'LEADER_MINOR_CIV_MILITARISTIC',
       'LEADER_MINOR_CIV_RELIGIOUS', 'LEADER_MINOR_CIV_SCIENTIFIC', 'LEADER_MINOR_CIV_TRADE');


-- needed for players without nfp
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType)
VALUES ('REQUIRES_PLOT_HAS_GRASS_FLOODPLAINS', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES'),
       ('REQUIRES_PLOT_HAS_PLAINS_FLOODPLAINS', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('REQUIRES_PLOT_HAS_GRASS_FLOODPLAINS', 'FeatureType', 'FEATURE_FLOODPLAINS_GRASSLAND'),
       ('REQUIRES_PLOT_HAS_PLAINS_FLOODPLAINS', 'FeatureType', 'FEATURE_FLOODPLAINS_PLAINS');


-- =============================================================
-- 马其顿
-- 城市不会产生厌战情绪。为军营建筑+40% [ICON_PRODUCTION] 生产力。军事学后，拥有皇家学堂的城市生产的兵种+1 [ICON_Strength] 战斗力。民族主义后，拥有皇家学堂的城市生产非平民单位时获得等同于其 [ICON_PRODUCTION] 生产力花费15%的 [ICON_CULTURE] 文化，+1 [ICON_Strength] 战斗力。

DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_TO_WORLDS_END'
AND ModifierId IN ('MAQIDUN_DAJUN_DIANSHU_1','MAQIDUN_DAJUN_DIANSHU_2','TRAIT_TOWORLDSEND_HEAL_ON_WONDER_CAPTURE');

DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_HELLENISTIC_FUSION' AND ModifierId IN
    ('TRAIT_HELLENISTIC_FUSION_ENCAMPMENT_EUREKA',
     'TRAIT_HELLENISTIC_FUSION_CAMPUS_EUREKA',
     'TRAIT_HELLENISTIC_FUSION_HOLY_SITE_INSPIRATION',
     'TRAIT_HELLENISTIC_FUSION_THEATER_INSPIRATION');


INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_LEADER_TO_WORLDS_END', 'MODIFIER_TRAIT_LEADER_TO_WORLDS_END_ECAMP');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_ECAMP', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_ECAMP', 'Amount', '40'),
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_ECAMP', 'DistrictType', 'DISTRICT_ENCAMPMENT');


INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_BASILIKOI_PAIDES', 'MODIFIER_TRAIT_LEADER_TO_WORLDS_END_GOLD');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId ) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_GOLD', 'MODIFIER_SINGLE_CITY_GRANT_YIELD_PER_UNIT_COST', 'NW_PLAYER_HAS_CIVIC_NATIONALISM');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_GOLD', 'YieldType', 'YIELD_CULTURE'),
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_GOLD', 'UnitProductionPercent', 15);



INSERT OR IGNORE INTO Types(Type, Kind)
VALUES ( 'AB_MODIFIER_MQD_JUNSIXUE','KIND_ABILITY'),
       ( 'AB_MODIFIER_MQD_MZ','KIND_ABILITY');
INSERT OR IGNORE INTO TypeTags(Type,Tag)
VALUES ('AB_MODIFIER_MQD_JUNSIXUE','CLASS_ALL_UNITS'),
       ( 'AB_MODIFIER_MQD_MZ','CLASS_ALL_UNITS');
INSERT OR IGNORE INTO UnitAbilities(UnitAbilityType,Inactive,Name,Description)
VALUES ( 'AB_MODIFIER_MQD_JUNSIXUE', 1 ,'LOC_AB_MODIFIER_MQD_JUNSIXUE_NAME','LOC_AB_MODIFIER_MQD_JUNSIXUE_NAME'),
       ( 'AB_MODIFIER_MQD_MZ', 1 ,'LOC_AB_MODIFIER_MQD_MZ_NAME','LOC_AB_MODIFIER_MQD_MZ_NAME');

INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
('AB_MODIFIER_MQD_JUNSIXUE', 'MODIFIER_AB_MODIFIER_MQD_JUNSIXUE_1'),
('AB_MODIFIER_MQD_MZ', 'MODIFIER_AB_MODIFIER_MQD_JUNSIXUE_1');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_AB_MODIFIER_MQD_JUNSIXUE_1', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_AB_MODIFIER_MQD_JUNSIXUE_1', 'Amount', '1');
INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES
('MODIFIER_AB_MODIFIER_MQD_JUNSIXUE_1', 'Perview', 'LOC_MODIFIER_AB_MODIFIER_MQD_JUNSIXUE_1');



INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_BASILIKOI_PAIDES', 'MODIFIER_TRAIT_LEADER_TO_WORLDS_END_AB1');
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_AB1', 'MODIFIER_SINGLE_CITY_GRANT_ABILITY_FOR_TRAINED_UNITS', 'NW_PLAYER_HAS_TECH_MILITARY_SCIENCE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_AB1', 'AbilityType', 'AB_MODIFIER_MQD_JUNSIXUE');

INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_BASILIKOI_PAIDES', 'MODIFIER_TRAIT_LEADER_TO_WORLDS_END_AB2');
INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_AB2', 'MODIFIER_SINGLE_CITY_GRANT_ABILITY_FOR_TRAINED_UNITS', 'NW_PLAYER_HAS_CIVIC_NATIONALISM');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_END_AB2', 'AbilityType', 'AB_MODIFIER_MQD_MZ');

-- RequirementSets
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
('NW_CITY_HAS_BUILDING_BASILIKOI_PAIDES', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
('NW_CITY_HAS_BUILDING_BASILIKOI_PAIDES', 'REQ_NW_CITY_HAS_BUILDING_BASILIKOI_PAIDES');
-- Requirements
INSERT INTO Requirements (RequirementId, RequirementType) VALUES
('REQ_NW_CITY_HAS_BUILDING_BASILIKOI_PAIDES', 'REQUIREMENT_CITY_HAS_BUILDING');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
('REQ_NW_CITY_HAS_BUILDING_BASILIKOI_PAIDES', 'BuildingType', 'BUILDING_BASILIKOI_PAIDES');



-- 区域+1 [ICON_FOOD] 食物，军营额外+1 [ICON_FOOD] 食物。拥有军营区域的城市建造区域及建筑时+10% [ICON_PRODUCTION] 生产力。政体内的一个军事卡槽变为通配符卡槽。

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION', 'MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_FOOD');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_FOOD', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_FOOD', 'Amount', '1'),
('MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_FOOD', 'YieldType', 'YIELD_FOOD');

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION', 'MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_PRODUCTION');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_PRODUCTION', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 0, 0, NULL, 'NW_DISTRICT_IS_DISTRICT_ENCAMPMENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_PRODUCTION', 'Amount', '1'),
('MODIFIER_TRAIT_CIVILIZATION_HELLENISTIC_FUSION_ADD_PRODUCTION', 'YieldType', 'YIELD_FOOD');


INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION', 'MODIFIER_TRAIT_LEADER_CULTUREEXPAND_DIS_PROD');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('MODIFIER_TRAIT_LEADER_CULTUREEXPAND_DIS_PROD', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION_MODIFIER', 'NW_CITY_HAS_DISTRICT_ENCAMPMENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_LEADER_CULTUREEXPAND_DIS_PROD', 'Amount', '10');

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION', 'MODIFIER_TRAIT_LEADER_CULTUREEXPAND_BUILDING_PRODUCTION_MODIFIER');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('MODIFIER_TRAIT_LEADER_CULTUREEXPAND_BUILDING_PRODUCTION_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION_MODIFIER', 'NW_CITY_HAS_DISTRICT_ENCAMPMENT');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_LEADER_CULTUREEXPAND_BUILDING_PRODUCTION_MODIFIER', 'Amount', '10'),
('MODIFIER_TRAIT_LEADER_CULTUREEXPAND_BUILDING_PRODUCTION_MODIFIER', 'IsWonder', '0');


INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_HELLENISTIC_FUSION', 'MODIFIER_TRAIT_LEADER_TO_WORLDS_SOLT');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_SOLT', 'MODIFIER_PLAYER_CULTURE_REPLACE_GOVERNMENT_SLOTS', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_TRAIT_LEADER_TO_WORLDS_SOLT', 'AddedGovernmentSlotType', 'SLOT_WILDCARD'),
('MODIFIER_TRAIT_LEADER_TO_WORLDS_SOLT', 'ReplacedGovernmentSlotType', 'SLOT_MILITARY'),
('MODIFIER_TRAIT_LEADER_TO_WORLDS_SOLT', 'ReplacesAll', '0');
