
-- 作为国际贸易路线的目的地，为起源城市+2 [ICON_Gold] 金币。+1 [ICON_tradeRoute] 贸易路线容量。每回合+1同盟点数。敌方间谍以己方城市为目标时，其效力降低一级。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。
UPDATE Buildings SET Description = 'LOC_CAC_BUILDING_GOV_CITYSTATES_EXPANSION2_DESCRIPTION' WHERE BuildingType = 'BUILDING_GOV_CITYSTATES';
DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_GOV_CITYSTATES';

INSERT INTO BuildingModifiers (BuildingType, ModifierId)
VALUES
('BUILDING_GOV_CITYSTATES', 'MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRY');
INSERT INTO Modifiers(ModifierId, ModifierType)
VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRY', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRY', 'Amount', '2'),
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRY', 'Domestic', '0'),
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRY', 'YieldType', 'YIELD_GOLD');


INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_GOV_CITYSTATES', 'MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRC');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRC', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_TRC', 'Amount', '1');

INSERT INTO BuildingModifiers (BuildingType, ModifierId)
VALUES
('BUILDING_GOV_CITYSTATES', 'MODIFIER_BUILDING_GOV_CITYSTATES_CAC_ALLIANCE_POINTS');
INSERT INTO Modifiers(ModifierId, ModifierType)
VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_ALLIANCE_POINTS', 'MODIFIER_PLAYER_ADJUST_ALLIANCE_POINTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_ALLIANCE_POINTS', 'Amount', '4');


INSERT INTO BuildingModifiers (BuildingType, ModifierId)
VALUES
('BUILDING_GOV_CITYSTATES', 'MODIFIER_BUILDING_GOV_CITYSTATES_CAC_SPY_BONUS');
INSERT INTO Modifiers(ModifierId, ModifierType)
VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_SPY_BONUS', 'MODIFIER_PLAYER_CITIES_ADJUST_SPY_BONUS');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES
('MODIFIER_BUILDING_GOV_CITYSTATES_CAC_SPY_BONUS', 'Amount', '1');
