-- Team_PVP_More_GreatPeople
-- Author: Nwflower
-- DateCreated: 2025-6-12 14:19:14
--------------------------------------------------------------
INSERT INTO IconDefinitions(Name,Atlas,'Index')VALUES
('ICON_GREATWORK_NW_MUSICIAN_CLASSICAL_11','ICON_ATLAS_GREATWORKS', 1),
('ICON_GREATWORK_NW_MUSICIAN_CLASSICAL_12','ICON_ATLAS_GREATWORKS', 1),
('ICON_GREATWORK_NW_MUSICIAN_MEDIEVAL_11','ICON_ATLAS_GREATWORKS', 1),
('ICON_GREATWORK_NW_MUSICIAN_MEDIEVAL_12','ICON_ATLAS_GREATWORKS', 1),
('ICON_GREATWORK_NW_MUSICIAN_RENAISSANCE_11','ICON_ATLAS_GREATWORKS', 1),
('ICON_GREATWORK_NW_MUSICIAN_RENAISSANCE_12','ICON_ATLAS_GREATWORKS', 1),
('ICON_GREATWORK_NW_MUSICIAN_RENAISSANCE_21','ICON_ATLAS_GREATWORKS', 1),
('ICON_GREATWORK_NW_MUSICIAN_RENAISSANCE_22','ICON_ATLAS_GREATWORKS', 1);