-- Team_PVP_More_GreatPeople
-- Author: Nwflower
-- DateCreated: 2025-6-12 14:19:14
--------------------------------------------------------------
DELETE
FROM GreatPersonIndividuals
WHERE GreatPersonIndividualType IN
      ('GREAT_PERSON_INDIVIDUAL_NW_WRITER_CLASSICAL_3',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_CLASSICAL_4',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_MEDIEVAL_3',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_MEDIEVAL_4',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_RENAISSANCE_3',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_RENAISSANCE_4',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_INDUSTRIAL_3',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_MODERN_3',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_ATOMIC_1',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_ATOMIC_2',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_INFORMATION_1',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_INFORMATION_2',
       'GREAT_PERSON_INDIVIDUAL_NW_WRITER_INFORMATION_3');