INSERT OR
REPLACE INTO LocalizedText(Language, Tag, Text)VALUES
('zh_Hans_CN', 'LOC_BELIEF_PAGODA_EXPANSION2_DESCRIPTION', '允许建造宝塔（+3 [ICON_Faith] 信仰值、每回合+1 [ICON_Favor] 外交支持）。'),
('zh_Hans_CN', 'LOC_BUILDING_BARRACKS_EXPANSION2_DESCRIPTION', '该城市中训练的所有近战和远程陆地单位+25%战斗经验值。[NEWLINE]战略资源储备+10（标准速度下）。'),
('zh_Hans_CN', 'LOC_BUILDING_STABLE_EXPANSION2_DESCRIPTION', '此城市生产的所有骑兵类和攻城类单位+25%战斗经验值。[NEWLINE]战略资源储备+10（标准速度下）。'),
('zh_Hans_CN', 'LOC_BUILDING_MARKET_EXPANSION1_DESCRIPTION', '+1 [ICON_TradeRoute] 贸易路线容量。'),
('zh_Hans_CN', 'LOC_BUILDING_LIGHTHOUSE_EXPANSION2_DESCRIPTION', '此城生产的所有海军单位+25%战斗经验值。此城的所有海岸单元格+1 [ICON_FOOD] 食物。如此城与海岸相邻，则+2 [ICON_HOUSING] 住房。+1 [ICON_TradeRoute] 贸易路线容量。'),
('zh_Hans_CN', 'LOC_BUILDING_MUSEUM_ART_DESCRIPTION', '可存放 [ICON_GreatWork_Landscape] 艺术巨作。'),
('zh_Hans_CN', 'LOC_BUILDING_MUSEUM_ARTIFACT_DESCRIPTION', '可存放 [ICON_GreatWork_Artifact] 文物。'),
('zh_Hans_CN', 'LOC_BUILDING_SUKIENNICE_EXPANSION1_DESCRIPTION', '波兰特色建筑。从此城开始的国际 [ICON_TradeRoute] 贸易路线+2 [ICON_Production] 生产力；国内 [ICON_TradeRoute] 贸易路线+4 [ICON_Gold] 金币。+1 [ICON_TradeRoute] 贸易路线容量。'),
('zh_Hans_CN', 'LOC_BUILDING_BASILIKOI_PAIDES_EXPANSION2_DESCRIPTION', '马其顿特色建筑。该城中训练的陆地近战、远程单位和伙友骑兵+25%战斗经验值。非平民单位在此城中创建时，获得等同于单位花费25%的 [ICON_SCIENCE] 科技值。[NEWLINE][NEWLINE]战略资源储备+10（标准速度下）。'),
('zh_Hans_CN', 'LOC_BUILDING_ORDU_EXPANSION2_DESCRIPTION', '蒙古特色建筑。其所在城市生产的轻重骑兵单位+1 [ICON_MOVEMENT] 移动力。其所在城市生产的所有骑兵类和攻城类单位+25%战斗经验值。[NEWLINE]战略资源储备+10（标准速度下）。'),
('zh_Hans_CN', 'LOC_BUILDING_POWER_PLANT_EXPANSION2_DESCRIPTION', '将任意数额的 [ICON_RESOURCE_URANIUM] 铀自动转换为 [ICON_Power] 电力，每回合可为周围6个单元格内的城市提供其所需电力：[NEWLINE][ICON_Bullet]1点 [ICON_RESOURCE_URANIUM] 铀 [ICON_PowerRight] 64点 [ICON_Power] 电力[NEWLINE][ICON_Bullet]会向大气层排放少量二氧化碳[NEWLINE]建成后发生核事故的概率会随着核电站老化而增加。其 [ICON_Production] 生产力和 [ICON_Science] 科技值加成延伸到6单元格内的所有市中心（前提是其尚未从其他的“发电厂”建筑获得加成。）'),
('zh_Hans_CN', 'LOC_DISTRICT_AQUEDUCT_ALT_DESCRIPTION', '城市的 [ICON_Food] 食物增长+20%；城市里的每位 [ICON_Citizen] 公民提供+0.5 [ICON_Food] 食物。[NEWLINE]区域从相邻河流、湖泊、绿洲或山脉引水，为该城市提供淡水资源。没有淡水资源的城市最多获得6个 [ICON_Housing] 住房。相反，已有淡水资源的城市 [ICON_Housing] 住房数量+2；若与地热裂缝相邻，提供+1 [ICON_Amenities]宜居度。干旱时可防止 [ICON_Food] 食物损失。必须修建在与市中心相邻的单元格中。军事工程师可消耗1次使用次数来完成水渠20%的修建进度。'),
('zh_Hans_CN', 'LOC_DISTRICT_BATH_EXPANSION2_ALT_DESCRIPTION', '促进城市发展的罗马特色区域。取代水渠，建造费用更低。[NEWLINE][NEWLINE]城市的 [ICON_Food] 食物增长+20%；城市里的每位 [ICON_Citizen] 公民提供+0.5 [ICON_Food] 食物。[NEWLINE]从相邻河流、湖泊、绿洲或山脉引水，为该城市提供淡水资源。尚未拥有淡水资源的城市最多获得6个 [ICON_Housing] 住房。已有淡水资源的城市则+2 [ICON_Housing] 住房。若与地热裂缝相邻，提供+1 [ICON_Amenities] 宜居度。在任何情况下，浴场都能额外提供+2 [ICON_Housing] 住房和+1 [ICON_Amenities] 宜居度。干旱时可防止 [ICON_Food] 食物损失。必须修建在与市中心相邻的单元格中。军事工程师可消耗1次使用次数来完成浴场20%的修建进度。'),
('zh_Hans_CN', 'LOC_DISTRICT_DAM_DESCRIPTION', '农场、种植园提供的 [ICON_FOOD] 食物+1。建造在泛滥平原单元格上的区域，可改善此江河流域旁的民生质量（但来自洪水的产出减半）。其可防止江河泛滥带来的损害，还可在干旱时防止 [ICON_Food] 食物损失。每条江河的泛滥平原中仅能建造1个（有文明建成便视为已建造），且江河必须至少穿过堤坝格位的两个面。军事工程师可消耗1次使用次数来完成堤坝20%的修建进度。'),
('zh_Hans_CN', 'LOC_DISTRICT_CANAL_DESCRIPTION', '建在平原上的区域，连接两块水域单元格或将一块水域单元格与市中心连接。+1 [ICON_TradeRoute] 贸易路线容量。如 [ICON_TradeRoute] 贸易路线途径此处，其将从目的地的区域处获得成倍 [ICON_Gold] 金币。运河可笔直穿过单元格，也可在其中进行60度转向。无法建造三向连接运河，且运河在其所建水路的两侧皆必须含有一个完整的陆地单元格。军事工程师可消耗1次使用次数来完成运河20%的修建进度。'),
('zh_Hans_CN', 'LOC_DISTRICT_PRESERVE_DESCRIPTION', '可基于魅力最高提供3点 [ICON_Housing] 住房。对相邻的中立单元格施放文化炸弹，并使其魅力增加3级。'),
('zh_Hans_CN', 'LOC_BUILDING_GROVE_DESCRIPTION', '为相邻迷人单元格+1 [ICON_FOOD] 食物、+1 [ICON_FAITH] 信仰值。为相邻惊艳单元格+2 [ICON_FOOD] 食物、+2 [ICON_FAITH] 信仰值、+2 [ICON_CULTURE] 文化值。'),
('zh_Hans_CN', 'LOC_BUILDING_SANCTUARY_DESCRIPTION', '为相邻迷人单元格+1 [ICON_SCIENCE] 科技值、+1 [ICON_GOLD] 金币。为相邻惊艳单元格+2 [ICON_SCIENCE] 科技值、+2 [ICON_GOLD] 金币、+2 [ICON_PRODUCTION] 生产力。'),
('zh_Hans_CN', 'LOC_DISTRICT_DIPLOMATIC_QUARTER_EXPANSION2_DESCRIPTION', '每回合影响力点数+1。通过外交，外国文明的每个代表团或大使馆将为您的文明提供+1 [ICON_FAVOR] 外交支持。如建在市中心旁，则+1 [ICON_ENVOY] 使者。敌方间谍将此区域和相邻区域当做目标时，其效果将降低2级。文明中一次仅限建造一座此区域。'),
('zh_Hans_CN', 'LOC_GREATPERSON_COMBAT_STRENGTH_AOE_SEA', '在两个单元格以内，为海军单位+5 [ICON_Strength] 战斗力和+1 [ICON_Movement] 移动力。'),
('zh_Hans_CN', 'LOC_GREATPERSON_COMBAT_STRENGTH_AOE_LAND', '在两个单元格以内，为陆地单位+5 [ICON_Strength] 战斗力和+1 [ICON_Movement] 移动力。'),
('zh_Hans_CN', 'LOC_RESOURCE_GOLD_NAME', '金矿石'),
('zh_Hans_CN', 'LOC_PEDIA_RESOURCES_PAGE_RESOURCE_GOLD_CHAPTER_HISTORY_PARA_1', '虽然19世纪初便已发现黄金，但直到1851年澳大利亚才陷入“淘金热”。挖掘的金矿石数量极大，以至于英国创办了悉尼铸币厂。这是英国硬币首次在本土之外进行铸造。黄金始终是澳大利亚利润丰厚的出口品之一。'),
('zh_Hans_CN', 'LOC_PROJECT_DECOMMISSION_COAL_POWER_PLANT_DESCRIPTION', '从此城市中移除燃煤发电厂及其全部效果。'),
('zh_Hans_CN', 'LOC_PROJECT_DECOMMISSION_OIL_POWER_PLANT_DESCRIPTION', '从此城市中移除燃油发电厂及其全部效果。'),
('zh_Hans_CN', 'LOC_PROJECT_DECOMMISSION_NUCLEAR_POWER_PLANT_DESCRIPTION', '从此城市中移除核电站及其全部效果。'),
('zh_Hans_CN', 'LOC_PROJECT_COTHON_CAPITAL_MOVE_DESCRIPTION', '完成时，将 [ICON_Capital] 首都迁至该城市。'),
('zh_Hans_CN', 'LOC_TRAIT_LEADER_FOUNDER_CARTHAGE_DESCRIPTION', '每个市政广场建筑与市政广场区域+1 [ICON_TradeRoute] 贸易路线容量。在拥有市政广场的城市中建造区域时+50% [ICON_Production] 生产力。'),
('zh_Hans_CN', 'LOC_PROJECT_ENHANCE_DISTRICT_ENCAMPMENT_DESCRIPTION', '基于区域的项目，每回合提供 [ICON_Gold] 金币、完成后提供 [ICON_GreatGeneral] 大将军点数。项目完成时，本城军营区域内的陆地军事单位获得1次强化升级。'),
('zh_Hans_CN', 'LOC_POLICY_SAMODERZHAVIYE_NAME', '帝王专制'),
('zh_Hans_CN', 'LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_SAMODERZHAVIYE_CHAPTER_HISTORY_PARA_1', '帝王专制是沙俄保守主义思想的重要支柱之一。而其他国家则根据帝王专制的哲学（沙皇永远正确），尝试将权力分散在顾问之间，或进行广泛统治。如果沙皇懒惰、无能、或不了解实际情况，这种制度的弊端便凸显无疑。 '),
('zh_Hans_CN', 'LOC_POLICY_DESPOTIC_PATERNALISM_NAME', '家长作风'),
('zh_Hans_CN', 'LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_DESPOTIC_PATERNALISM_CHAPTER_HISTORY_PARA_1', '塔克·查洛恩提拉那在著作中提到，冷战时期的东南亚是特殊“家长作风”政策的发源地。这种政策将权力赋予当地重要的政治强人，同时限制独立的思想和行动。印尼的苏哈托或泰国的沙立便是典型范例。这种体系扼杀了自由探索，但专制家长主义者也能通过这种手段有效扼制反对意见。 '),
('zh_Hans_CN', 'LOC_POLICY_DECENTRALIZATION_NAME', '去中心化'),
('zh_Hans_CN', 'LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_DECENTRALIZATION_CHAPTER_HISTORY_PARA_1', '面对社会崩溃（如黑暗时代），一些文明转向中央集权的严酷统治，而另一些文明则反其道而行之，让周边地区拥有更高自治权。随着拜占庭帝国的衰落，君士坦丁堡的人口便是通过这样的方式流向了小城镇和农村。通过这种方式，中央抓住了最后一根稻草，让人心不至于四散崩塌，在艰难岁月中多少也能起到一定作用。'),
('zh_Hans_CN', 'LOC_POLICY_SOFT_TARGETS_NAME', '软目标'),
('zh_Hans_CN', 'LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_SOFT_TARGETS_CHAPTER_HISTORY_PARA_1', '纪律严明、不会随意进行掠夺的军队是社会运转良好的重要标志。但在黑暗时代中，信条也可能会被背弃。在偏爱软目标（平民）、并将掠夺视为发财机会的军队里，士兵会更倾向于追逐容易抢夺的战利品，而非军事战略目标。这种行为会增加对城市和平民的破坏，同时降低战争的效力。'),
('zh_Hans_CN', 'LOC_POLICY_SAMODERZHAVIYE_DESCRIPTION', '[ICON_CAPITAL] 首都+50% [ICON_PRODUCTION] 生产力。[NEWLINE]减益：所有 [ICON_Governor] 总督都会遭到陷害，且无法调职。'),
('zh_Hans_CN', 'LOC_POLICY_DESPOTIC_PATERNALISM_DESCRIPTION', '拥有 [ICON_Governor] 总督的城市每回合忠诚度+4。[NEWLINE]减益：没有就职 [ICON_Governor] 总督的城市-15% [ICON_Science] 科技值、-15% [ICON_Culture] 文化值。'),
('zh_Hans_CN', 'LOC_POLICY_DECENTRALIZATION_DESCRIPTION', '拥有6点或更少 [ICON_CITIZEN] 人口的城市每回合忠诚度+4。[NEWLINE]减益：[ICON_CITIZEN] 人口超过6点的城市-15% [ICON_Gold] 金币。'),
('zh_Hans_CN', 'LOC_POLICY_SOFT_TARGETS_DESCRIPTION', '进攻城市和区域时+10 [ICON_Strength] 战斗力。[NEWLINE]减益：与单位作战时-3 [ICON_Strength] 战斗力。'),
('zh_Hans_CN', 'LOC_ABILITY_SOFT_TARGETS_DEFENDING_CITY_RANGE_DESCRIPTION', '进攻城市时，“软目标政策”提供+10 [ICON_Strength] 战斗力'),
('zh_Hans_CN', 'LOC_ABILITY_SOFT_TARGETS_ATTACKING_DISTRICTS_DESCRIPTION', '进攻区域时，“软目标政策”提供+10 [ICON_Strength] 战斗力。'),
('zh_Hans_CN', 'LOC_ABILITY_SOFT_TARGETS_ATTACKING_UNITS_DESCRIPTION', '与单位作战时，“软目标政策”提供-3 [ICON_Strength] 战斗力。'),
('zh_Hans_CN', 'LOC_ABILITY_ABILITY_SOFT_TARGETS_DEFENDING_CITY_RANGE_COMPLEX_COMBAT_STRENGTH_PREVIEW_DESCRIPTION', '软目标政策+{1_Amount} [ICON_Strength] 战斗力。'),
('zh_Hans_CN', 'LOC_ABILITY_SOFT_TARGETS_ATTACKING_DISTRICTS_COMBAT_STRENGTH_PREVIEW_DESCRIPTION', '软目标政策+{1_Amount} [ICON_Strength] 战斗力。'),
('zh_Hans_CN', 'LOC_ABILITY_SOFT_TARGETS_ATTACKING_UNITS_COMBAT_STRENGTH_PREVIEW_DESCRIPTION', '软目标政策提供[COLOR_RED]{1_Amount}[ENDCOLOR][ICON_Strength] 战斗力。'),
('zh_Hans_CN', 'LOC_BUILDING_GOV_CONQUEST_DESCRIPTION', '在此城中生产军事单位时 [ICON_Production] 生产力+30%。占领一座敌方城市后，所有城市将获得20%的 [ICON_Production] 生产力加成，效果持续5回合。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。'),
('zh_Hans_CN', 'LOC_BUILDING_GOV_TALL_DESCRIPTION', '[ICON_CAPITAL] 首都和有 [ICON_Governor] 总督的城市+2 [ICON_Amenities] 宜居度、+4 [ICON_Housing] 住房。[NEWLINE]无 [ICON_Governor] 总督的非[ICON_CAPITAL] 首都城市-2忠诚度。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。'),
('zh_Hans_CN', 'LOC_BUILDING_GOV_SPIES_DESCRIPTION', '间谍容量+2。[NEWLINE]所有间谍行动的成功率上升。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。'),
('zh_Hans_CN', 'LOC_BUILDING_GOV_CITYSTATES_EXPANSION2_DESCRIPTION', '每回合影响力点数+2。+3 [ICON_Favor] 外交支持。征召城邦单位消耗的 [ICON_Gold] 金币减半。[NEWLINE]如您是城邦的宗主国，则城邦单位+4 [ICON_Strength] 战斗力（征召单位包含在内）。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。'),
('zh_Hans_CN', 'LOC_BUILDING_GOV_CULTURE_DESCRIPTION', '+10 [ICON_Tourism] 旅游业绩。提供任意4个巨作槽位。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。'),
('zh_Hans_CN', 'LOC_GOVT_INHERENT_BONUS_THEOCRACY_XP1', '神学战争中+5 [ICON_Religion] 宗教战斗力。[NEWLINE][ICON_CAPITAL] 首都和有 [ICON_Governor] 总督的城市中每位 [ICON_Citizen] 公民将+0.5点 [ICON_Faith] 信仰值。'),
('zh_Hans_CN', 'LOC_GOVT_INHERENT_BONUS_MERCHREP_XP1', '[ICON_CAPITAL] 首都和有 [ICON_Governor] 总督的城市产出的 [ICON_GOLD] 金币+10%。'),
('zh_Hans_CN', 'LOC_GOVT_INHERENT_BONUS_COMMUNISM_XP1', '[ICON_CAPITAL] 首都和有 [ICON_Governor] 总督的城市中每位 [ICON_Citizen] 公民将提供0.6点 [ICON_Production] 生产力。');
