INSERT INTO IconDefinitions
    (Name, Atlas, 'Index')
VALUES ('ICON_GOVERNMENT_BULUO', 'ICON_ATLAS_GOVERNMENTS', 0),
       ('ICON_GOVERNMENT_PHARAOH', 'ICON_ATLAS_GOVERNMENTS', 0),
       ('ICON_GOVERNMENT_FENFENG', 'ICON_ATLAS_GOVERNMENTS', 0);