---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025-5-22 13:40:31
---

-- 合适的相邻单元格
function GetOKPlot(pUnit)
    local unitInfo = GameInfo.Units[pUnit:GetType()]
	local plots = Map.GetAdjacentPlots(pUnit:GetX(), pUnit:GetY())

	-- 如果是有行动力的陆军单位
	-- 如果相邻可通行水域就return false
	if unitInfo.FormationClass == 'FORMATION_CLASS_LAND_COMBAT' and pUnit:GetMovementMovesRemaining() > 0 then
		for _, pNeighborPlot in ipairs(plots) do
			if pNeighborPlot:IsWater() then
				-- 看一下该单元格是否可以扬帆
				local flat = false;
				for loop, ppUnit in ipairs(Units.GetUnitsInPlot(pNeighborPlot)) do
					if(ppUnit ~= nil) then
						if ppUnit:GetOwner() ~= pUnit:GetOwner() then
							flat = true
						end
					end
				end
				if flat == false then
					return pNeighborPlot:GetIndex()
				end
			end
		end
	end

	-- 如果是有行动力的海军单位
	if unitInfo.FormationClass == 'FORMATION_CLASS_NAVAL' and pUnit:GetMovementMovesRemaining() > 0 then
		for _, pNeighborPlot in ipairs(plots) do
			if (not pNeighborPlot:IsWater() and not pNeighborPlot:IsMountain()) then
				-- 看一下该单元格是否可以登陆
				local flat = false;
				for loop, ppUnit in ipairs(Units.GetUnitsInPlot(pNeighborPlot)) do
					if(ppUnit ~= nil) then
						if ppUnit:GetOwner() ~= pUnit:GetOwner() then
							flat = true
						end
					end
				end
				if flat == false then
					return pNeighborPlot:GetIndex()
				end
			end
		end
	end
end

function NWAmericanTransfer(iPlayerID, params)
	local pUnit = UnitManager.GetUnit(iPlayerID, params.activeUnit);
    -- 先获得单位信息
    local UnitInfo = GameInfo.Units[pUnit:GetType()]
    -- 镜像单位
    local pickUnit = pUnit:GetProperty('OTTOMAN_PICK')
    if pickUnit == nil then
        for row in GameInfo.American_Unit() do
            if row.LandUnit == UnitInfo.UnitType then
                pickUnit = row.NavalUnit
                break;
            elseif row.NavalUnit == UnitInfo.UnitType then
                pickUnit = row.LandUnit
                break;
            end
        end
    end
    -- 单位血量情况
    local pDamage = pUnit:GetDamage()
    -- 单位军团军队情况
    local militaryFormation = pUnit:GetMilitaryFormation();

    -- new一个单位
    local iPlotIndex = GetOKPlot(pUnit)
    local iX,iY = Map.GetPlotLocation(iPlotIndex)
    local newUnit = UnitManager.InitUnit(iPlayerID,pickUnit,iX,iY);
    if pDamage>0 then
        newUnit:ChangeDamage(pDamage);
    end
    -- 存储镜像单位信息
    newUnit:SetProperty('OTTOMAN_PICK',UnitInfo.UnitType)
    UnitManager.Kill(pUnit);


    if (militaryFormation == MilitaryFormationTypes.CORPS_FORMATION) then
        newUnit:SetMilitaryFormation(MilitaryFormationTypes.CORPS_FORMATION)
    elseif (militaryFormation == MilitaryFormationTypes.ARMY_FORMATION) then
        newUnit:SetMilitaryFormation(MilitaryFormationTypes.ARMY_FORMATION)
    end
    UnitManager.FinishMoves(newUnit);
end



function NWAmericanGetSight(iPlayerID, params)
	local pPlot = Map.GetPlot(params.PlotX, params.PlotY)
	local pVis = PlayersVisibility[iPlayerID];
	pVis:ChangeVisibilityCount(pPlot:GetIndex(), 1);
end

function initialize()
	GameEvents.NWAmericanTransfer.Add(NWAmericanTransfer);
	GameEvents.NWAmericanGetSight.Add(NWAmericanGetSight);
end
Events.LoadScreenClose.Add( initialize);
print('NWAmericanTransfer is Loaded');