INSERT INTO Types (Type, Kind) VALUES
('LEADER_SIQI_L0007', 'KIND_LEADER'),
('TRAIT_LEADER_SIQI_L0007', 'KIND_TRAIT');

INSERT INTO Traits (TraitType, Name, Description) VALUES
('TRAIT_LEADER_SIQI_L0007', 'LOC_TRAIT_LEADER_SIQI_L0007_NAME', 'LOC_TRAIT_LEADER_SIQI_L0007_DESCRIPTION');

INSERT INTO Leaders (LeaderType, Name, Sex, InheritFrom, SceneLayers) VALUES
('LEADER_SIQI_L0007', 'LOC_LEADER_SIQI_L0007_NAME', 'Female', 'LEADER_DEFAULT', 4);

INSERT INTO LeaderQuotes (LeaderType, Quote) VALUES
('LEADER_SIQI_L0007', 'LOC_PEDIA_LEADERS_PAGE_SIQI_L0007_QUOTE');

INSERT INTO LeaderTraits (LeaderType, TraitType) VALUES
('LEADER_SIQI_L0007', 'TRAIT_LEADER_SIQI_L0007'),
('LEADER_SIQI_L0007', 'TRAIT_UNIT_SIQI_U0007');

INSERT INTO LoadingInfo (LeaderType, ForegroundImage, BackgroundImage, PlayDawnOfManAudio, LeaderText) VALUES
('LEADER_SIQI_L0007', 'IMG_SIQI_L0007_Leaders_Foreground.png', 'IMG_SIQI_L0007_Loading_Background.png', 1, 'LOC_LOADING_INFO_LEADER_SIQI_L0007');

INSERT INTO DiplomacyInfo (Type, BackgroundImage) VALUES
('LEADER_SIQI_L0007', 'IMG_SIQI_L0007_Loading_Background.png');

-- INSERT INTO Types (Type, Kind) VALUES
-- ('TRAIT_AGENDA_LEADER_SIQI_L0007', 'KIND_TRAIT');

-- INSERT INTO Traits (TraitType, Name, Description) VALUES
-- ('TRAIT_AGENDA_LEADER_SIQI_L0007', 'LOC_TRAIT_AGENDA_LEADER_SIQI_L0007_NAME', 'LOC_TRAIT_AGENDA_LEADER_SIQI_L0007_DESCRIPTION');

-- INSERT INTO Agendas (AgendaType, Name, Description) VALUES
-- ('AGENDA_LEADER_SIQI_L0007', 'LOC_AGENDA_LEADER_SIQI_L0007_NAME', 'LOC_AGENDA_LEADER_SIQI_L0007_DESCRIPTION');

-- INSERT INTO HistoricalAgendas (LeaderType, AgendaType) VALUES
-- ('LEADER_SIQI_L0007', 'AGENDA_LEADER_SIQI_L0007');

-- INSERT INTO AgendaTraits (AgendaType, TraitType) VALUES
-- ('AGENDA_LEADER_SIQI_L0007', 'TRAIT_AGENDA_LEADER_SIQI_L0007');
