INSERT INTO Types (Type, Kind) VALUES
('UNIT_SIQI_U0007', 'KIND_UNIT'),
('TRAIT_UNIT_SIQI_U0007', 'KIND_TRAIT'),
('UNIT_SIQI_U0007_2', 'KIND_UNIT'),
('TRAIT_UNIT_SIQI_U0007_2', 'KIND_TRAIT');

INSERT INTO Traits (TraitType, Name, Description) VALUES
('TRAIT_UNIT_SIQI_U0007', 'LOC_TRAIT_UNIT_SIQI_U0007_NAME', 'LOC_TRAIT_UNIT_SIQI_U0007_DESCRIPTION'),
('TRAIT_UNIT_SIQI_U0007_2', 'LOC_TRAIT_UNIT_SIQI_U0007_2_NAME', 'LOC_TRAIT_UNIT_SIQI_U0007_2_DESCRIPTION');

INSERT INTO UnitAiInfos (UnitType, AiType)
SELECT 'UNIT_SIQI_U0007', AiType FROM UnitAiInfos WHERE UnitType = 'UNIT_BIPLANE'
UNION SELECT 'UNIT_SIQI_U0007_2', AiType FROM UnitAiInfos WHERE UnitType = 'UNIT_CARAVEL';

INSERT INTO Tags (Tag, Vocabulary) VALUES ('CLASS_SIQI_U0007_2', 'ABILITY_CLASS');
INSERT INTO TypeTags (Type, Tag) VALUES ('UNIT_SIQI_U0007_2', 'CLASS_SIQI_U0007_2');

INSERT INTO TypeTags (Type, Tag)
SELECT 'UNIT_SIQI_U0007', Tag FROM TypeTags WHERE Type = 'UNIT_BIPLANE'
UNION SELECT 'UNIT_SIQI_U0007_2', Tag FROM TypeTags WHERE Type = 'UNIT_CARAVEL';

INSERT INTO UnitReplaces (CivUniqueUnitType, ReplacesUnitType) VALUES
('UNIT_SIQI_U0007', 'UNIT_BIPLANE'),
('UNIT_SIQI_U0007_2', 'UNIT_CARAVEL');

INSERT INTO Units (
    UnitType,
    Name,
    BaseSightRange,
    BaseMoves,
    Combat,
    RangedCombat,
    Range,
    Bombard,
    Domain,
    FormationClass,
    Cost,
    PopulationCost,
    FoundCity,
    FoundReligion,
    MakeTradeRoute,
    EvangelizeBelief,
    LaunchInquisition,
    RequiresInquisition,
    BuildCharges,
    ReligiousStrength,
    ReligionEvictPercent,
    SpreadCharges,
    ReligiousHealCharges,
    ExtractsArtifacts,
    Description,
    Flavor,
    CanCapture,
    CanRetreatWhenCaptured,
    TraitType,
    AllowBarbarians,
    CostProgressionModel,
    CostProgressionParam1,
    PromotionClass,
    InitialLevel,
    NumRandomChoices,
    PrereqTech,
    PrereqCivic,
    PrereqDistrict,
    PrereqPopulation,
    LeaderType,
    CanTrain,
    StrategicResource,
    PurchaseYield,
    MustPurchase,
    Maintenance,
    Stackable,
    AirSlots,
    CanTargetAir,
    PseudoYieldType,
    ZoneOfControl,
    AntiAirCombat,
    Spy,
    WMDCapable,
    ParkCharges,
    IgnoreMoves,
    TeamVisibility,
    ObsoleteTech,
    ObsoleteCivic,
    MandatoryObsoleteTech,
    MandatoryObsoleteCivic,
    AdvisorType,
    EnabledByReligion,
    TrackReligion,
    DisasterCharges,
    UseMaxMeleeTrainedStrength,
    ImmediatelyName,
    CanEarnExperience
) SELECT
    'UNIT_SIQI_U0007',
    'LOC_UNIT_SIQI_U0007_NAME',
    BaseSightRange,
    BaseMoves,
    Combat+1,
    RangedCombat,
    Range,
    Bombard,
    Domain,
    FormationClass,
    Cost*1.05,
    PopulationCost,
    FoundCity,
    FoundReligion,
    MakeTradeRoute,
    EvangelizeBelief,
    LaunchInquisition,
    RequiresInquisition,
    BuildCharges,
    ReligiousStrength,
    ReligionEvictPercent,
    SpreadCharges,
    ReligiousHealCharges,
    ExtractsArtifacts,
    'LOC_UNIT_SIQI_U0007_DESCRIPTION',
    Flavor,
    CanCapture,
    CanRetreatWhenCaptured,
    'TRAIT_UNIT_SIQI_U0007',
    AllowBarbarians,
    CostProgressionModel,
    CostProgressionParam1,
    PromotionClass,
    InitialLevel,
    NumRandomChoices,
    PrereqTech,
    PrereqCivic,
    PrereqDistrict,
    PrereqPopulation,
    LeaderType,
    CanTrain,
    StrategicResource,
    PurchaseYield,
    MustPurchase,
    Maintenance,
    Stackable,
    AirSlots,
    CanTargetAir,
    PseudoYieldType,
    ZoneOfControl,
    AntiAirCombat,
    Spy,
    WMDCapable,
    ParkCharges,
    IgnoreMoves,
    TeamVisibility,
    ObsoleteTech,
    ObsoleteCivic,
    MandatoryObsoleteTech,
    MandatoryObsoleteCivic,
    AdvisorType,
    EnabledByReligion,
    TrackReligion,
    DisasterCharges,
    UseMaxMeleeTrainedStrength,
    ImmediatelyName,
    CanEarnExperience
FROM Units
WHERE UnitType = 'UNIT_BIPLANE'
UNION SELECT
    'UNIT_SIQI_U0007_2',
    'LOC_UNIT_SIQI_U0007_2_NAME',
    BaseSightRange,
    BaseMoves,
    Combat-1,
    RangedCombat,
    Range,
    Bombard,
    Domain,
    FormationClass,
    Cost*0.95,
    PopulationCost,
    FoundCity,
    FoundReligion,
    MakeTradeRoute,
    EvangelizeBelief,
    LaunchInquisition,
    RequiresInquisition,
    BuildCharges,
    ReligiousStrength,
    ReligionEvictPercent,
    SpreadCharges,
    ReligiousHealCharges,
    ExtractsArtifacts,
    'LOC_UNIT_SIQI_U0007_2_DESCRIPTION',
    Flavor,
    CanCapture,
    CanRetreatWhenCaptured,
    'TRAIT_UNIT_SIQI_U0007_2',
    AllowBarbarians,
    CostProgressionModel,
    CostProgressionParam1,
    PromotionClass,
    InitialLevel,
    NumRandomChoices,
    PrereqTech,
    PrereqCivic,
    PrereqDistrict,
    PrereqPopulation,
    LeaderType,
    CanTrain,
    StrategicResource,
    PurchaseYield,
    MustPurchase,
    Maintenance,
    Stackable,
    AirSlots,
    CanTargetAir,
    PseudoYieldType,
    ZoneOfControl,
    AntiAirCombat,
    Spy,
    WMDCapable,
    ParkCharges,
    IgnoreMoves,
    TeamVisibility,
    ObsoleteTech,
    ObsoleteCivic,
    MandatoryObsoleteTech,
    MandatoryObsoleteCivic,
    AdvisorType,
    EnabledByReligion,
    TrackReligion,
    DisasterCharges,
    UseMaxMeleeTrainedStrength,
    ImmediatelyName,
    CanEarnExperience
FROM Units
WHERE UnitType = 'UNIT_CARAVEL';


INSERT INTO Units_XP2 (UnitType, ResourceMaintenanceAmount, ResourceCost, ResourceMaintenanceType, TourismBomb, CanEarnExperience, TourismBombPossible, CanFormMilitaryFormation, MajorCivOnly, CanCauseDisasters, CanSacrificeUnits)
SELECT 'UNIT_SIQI_U0007', ResourceMaintenanceAmount, ResourceCost, ResourceMaintenanceType, TourismBomb, CanEarnExperience, TourismBombPossible, CanFormMilitaryFormation, MajorCivOnly, CanCauseDisasters, CanSacrificeUnits FROM Units_XP2 WHERE UnitType = 'UNIT_BIPLANE';

INSERT INTO UnitUpgrades (Unit, UpgradeUnit)
SELECT 'UNIT_SIQI_U0007', UpgradeUnit FROM UnitUpgrades WHERE Unit = 'UNIT_BIPLANE'
UNION SELECT 'UNIT_SIQI_U0007_2', UpgradeUnit FROM UnitUpgrades WHERE Unit = 'UNIT_CARAVEL';