INSERT OR REPLACE INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('ICON_BUILDING_GILDED_Shipyard', 'ICON_ATLAS_ETHIOPIA_BUILDINGS', '4'),
('ICON_BUILDING_GILDED_Shipyard_FOW', 'ICON_ATLAS_ETHIOPIA_BUILDINGS_FOW', '4');

