-- GreatJieshe
-- Author: QIANCHUANBAILANG
-- DateCreated: 2025-8-7 22:45:53
--------------------------------------------------------------
-- 冻土可改田
INSERT INTO GameModifiers (ModifierId) VALUES
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN', 'MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN', 0, 0, 0, NULL, 'PLAYER_IS_HUMAN');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN', 'ImprovementType', 'IMPROVEMENT_FARM'),
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN', 'TerrainType', 'TERRAIN_TUNDRA');
-- Custom ModifierType
INSERT INTO Types (Type, Kind) VALUES
('MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN', 'KIND_MODIFIER');
INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES
('MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN', 'COLLECTION_ALL_CITIES', 'EFFECT_ADJUST_IMPROVEMENT_VALID_TERRAIN');


INSERT INTO GameModifiers (ModifierId) VALUES
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN2');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN2', 'MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN', 0, 0, 0, NULL, 'PLAYER_IS_HUMAN_AND_HAS_TUMU');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN2', 'ImprovementType', 'IMPROVEMENT_FARM'),
('MODIFIER_MODIFIER_NW_ALL_CITIES_ADJUST_IMPROVEMENT_VALID_TERRAIN2', 'TerrainType', 'TERRAIN_TUNDRA_HILLS');
-- RequirementSets
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
('PLAYER_IS_HUMAN_AND_HAS_TUMU', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
('PLAYER_IS_HUMAN_AND_HAS_TUMU', 'REQ_NW_PLAYER_IS_HUMAN'),
('PLAYER_IS_HUMAN_AND_HAS_TUMU', 'REQ_NW_HAS_TUMU');
-- Requirements
INSERT INTO Requirements (RequirementId, RequirementType) VALUES
('REQ_NW_PLAYER_IS_HUMAN', 'REQUIREMENT_PLAYER_IS_HUMAN'),
('REQ_NW_HAS_TUMU', 'REQUIREMENT_PLAYER_HAS_CIVIC');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES
('REQ_NW_HAS_TUMU', 'CivicType', 'CIVIC_CIVIL_ENGINEERING');

DELETE FROM Types WHERE Type = 'RESOURCE_ANTIQUITY_SITE';
DELETE FROM Types WHERE Type = 'RESOURCE_SHIPWRECK';